{{- if and .Values.common.totalInstall .Values.chaos.enabled  }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos
  namespace: {{ .Values.namespace }}
  labels:
    project: {{ .Values.project }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.project }}:chaos
  namespace: {{ .Values.namespace }}
  labels:
    project: {{ .Values.project }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.project }}:chaos
  namespace: {{ .Values.namespace }}
  labels:
    project: {{ .Values.project }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.project }}:chaos
subjects:
- kind: ServiceAccount
  name: chaos
{{- end }}